### ISSUE TITLE
Can it function with a set of tripple non-overlapping mono cameras?

### ISSUE THREAD

**Issue by gfr-misha** [MAVIS-SLAM/OpenMAVIS#8]
Hi, thanks for your impressive work! We have a drone with 3 cameras each 120 deg FOV on 3 sides, however, their views do not overlap. Is there a chance that MAVIS-SLAM can function in this scenario? If not maybe you are aware of any package that can?
Many thanks in advance!

**Comment by 1fwang** [comment]
> Hi, thanks for your impressive work! We have a drone with 3 cameras each 120 deg FOV on 3 sides, however, their views do not overlap. Is there a chance that MAVIS-SLAM can function in this scenario? If not maybe you are aware of any package that can? Many thanks in advance!

Hi, thanks for your message.

Unfortunately, openMAVIS does not support 3 non-overlapping cameras since it uses stereo camera as initialization strategy(faster and more reliable), you can definately do some changes on it but requires additional effort(maybe not too much, but needs some experience and understanding on ORB-SLAM3). 

For other packages you might use, I believe OKVIS2 could be interesting for you: https://github.com/smartroboticslab/okvis2

**Comment by gfr-misha** [comment]
Thanks for your quick response! That's a shame, I wanted to use a solution based on ORB-SLAM3 since it's quite popular in the community, but I'll check okvis2 out. All the best and thanks for your work on the subject!

**Comment by 1fwang** [comment]
> Thanks for your quick response! That's a shame, I wanted to use a solution based on ORB-SLAM3 since it's quite popular in the community, but I'll check okvis2 out. All the best and thanks for your work on the subject!

Would let you know once the MAVIS supports such setup, stay tuned :)
